### ISSUE TITLE
show moderator only fields not to signatory

### ISSUE THREAD

**Issue by rrustema** [petities/petitions.eu#111]
a logged in user can see fields that are for the moderator only: petition type, petition status, subdomain.

**Comment by spreeker** [comment]
In the show petition view? in the detail box?

**Comment by spreeker** [comment]
in the code it looks correct

```
   - if(user_signed_in? && current_user.has_role?(:admin, @petition)) 

     div.start-petition-form-row                                      
       div.start-petition-form-cell.input                             
          div.start-petition-form-cell-title= t('start.form.petition_ty
              = f.select :petition_type_id,                                
```

**Comment by rrustema** [comment]
in the edit view (of their own petition). 

![screen shot 2015-12-19 at 16 53 30](https://cloud.githubusercontent.com/assets/98476/11913808/1be0213e-a671-11e5-9e9f-9b2fad3edc7b.png)
