### ISSUE TITLE
add custom additional fields in confirm screen if any

### ISSUE THREAD

**Issue by rrustema** [petities/petitions.eu#125]
Petition types can have custom additional description fields. These should show in the signature confirmation form as explanations to the input field. Replacing the (internationalised) fields with explanations.

**Comment by spreeker** [comment]
I think this violates the carefully build international behaviour of the website.
We can put those texts in yml files like  'en.confirm_lables.yml'
and have those loaded conditionally.

**Comment by rrustema** [comment]
yes, that is less messy and more structured
