### ISSUE TITLE
direct link to signature in signature list

### ISSUE THREAD

**Issue by rrustema** [petities/petitions.eu#173]
direct link to signature in signature list in petition signatures show (list) view does not seem to work

**Comment by rrustema** [comment]
does seem to work, further testing needed

**Comment by spreeker** [comment]
If there is a Javascript error the lookup can fail since the scrolling is
implemented in Javascript.

**Comment by rrustema** [comment]
https://github.com/petities/petitions.eu/commit/8ace483e310b5b928fdb5dafc09b71b25449d4ec

**Comment by rrustema** [comment]
there is some kind of error, unclear for the end user why. 

https://opendomein.nl/cerb5/display/JBW-59895-489

**Comment by rrustema** [comment]
tested, it works...
