### ISSUE TITLE
links under news items do not show

### ISSUE THREAD

**Issue by rrustema** [petities/petitions.eu#178]
the table newsitems has the field url and url_text (the latter sometimes empty). The link does not show ever, which makes many newsitems pointless. The link should show with the link itself as text when url_text is empty.

**Comment by spreeker** [comment]
we have markdown now.

**Comment by rrustema** [comment]
legacy newsitems are not converted to the markdown layout, which make the newsitem pointless

**Comment by skoolstra** [comment]
This was implemented in e5e894a by @rrustema.
