### ISSUE TITLE
subdomains preceded by www should also work

### ISSUE THREAD

**Issue by rrustema** [petities/petitions.eu#190]
See this tweet https://twitter.com/petities/status/683404740353503232
Some users put www before the petition shortlink, even before the subdomain. This worked in the previous website.

**Comment by johankok** [comment]
Alle pages are served via https in the new website. The wildcard certificate supports just one level of subdomains. You can use `https://<subdomain>.petities.nl/`, but `https://<subsubdomain>.<subdomain>.petities.nl/` is not valid.

The http-to-https rewrite rules are now adjusted. The extra `www.` will be removed. This will probably fix most occurrences for this error. See for example http://www.kruiskruid.petities.nl/

``` bash
[johan@boy ~]$ curl -I http://kruiskruid.petities.nl
HTTP/1.1 301 Moved Permanently
[...]
Location: https://kruiskruid.petities.nl/
[johan@boy ~]$ curl -I http://www.kruiskruid.petities.nl
HTTP/1.1 301 Moved Permanently
[...]
Location: https://kruiskruid.petities.nl/
```
