### ISSUE TITLE
improved check on e-mail address syntax

### ISSUE THREAD

**Issue by rrustema** [petities/petitions.eu#195]
signatories enter strange stuff which does not comply in any way:
- with several @-signs
- with comma's instead of dots
  etc. 

Improved check of e-mail syntax needed

**Comment by rrustema** [comment]
Hoi Simon,

Dank je!

**Comment by rrustema** [comment]
according to a bounce, someone signed with an address like: "r..rustema"@hetnet.nl

which the form should have prevented or perhaps even correct by deleting the " and replacing a double dots with one

**Comment by skoolstra** [comment]
This was fixed in almost a year ago (test included below). Closing this issue, please reopen if you still see addresses that should not have been validated.

```ruby
irb(main):001:0> signature = NewSignature.new(person_email: 'r..rustema"@hetnet.nl')
irb(main):002:0> signature.valid?
=> false
irb(main):003:0> signature.errors[:person_email]
=> ["is ongeldig"]
```
