### ISSUE TITLE
petitioner is not allowed to write a news update

### ISSUE THREAD

**Issue by rrustema** [petities/petitions.eu#210]
See complaint  https://opendomein.nl/cerb5/display/PPM-11848-786

**Comment by spreeker** [comment]
Is this only the case for older petitions or for all petitions?

I do not have access to complaint.

**Comment by rrustema** [comment]
just created a petition for testing purposes at https://petities.nl/petitions/petitionarissen-moeten-een-nieuwsbericht-kunnen-publiceren/ both user and pw is spam@reinder.rustema.nl (for now)

**Comment by spreeker** [comment]
a158ff9076f965749b6c0f5b48511c5a2f1a88c8 undid my abuse of has_role
