### ISSUE TITLE
confirmation troubles

### ISSUE THREAD

**Issue by rrustema** [petities/petitions.eu#218]
signatories complain they can not confirm
meanwhile they actually already confirmed, but the confirmation page asks to confirm, but does thank for the confirmation
also, when using the update button, there is no feedback (thank you), it is asif the button does not work

**Comment by spreeker** [comment]
Active rate werd verkeerd uitgerekent in sommige gevallen.

**Comment by spreeker** [comment]
8c84dda8df23009ad3952b526085e108acd89ced

we should add some more tests...
