### ISSUE TITLE
some signatories can not confirm

### ISSUE THREAD

**Issue by rrustema** [petities/petitions.eu#219]
signatories of petition 3253 and 17371 and 17107 and 17491 can not confirm/update their signature
to replicate:
- take a unique key from a signatory for any of these petitions from the signatures table
- https://petities.nl/signatures/INSERTKEYHERE/confirm
  and clicking on the 'update' button does not give the 'thank you' feedback. 
  Signatories of other petitions do not have this issue.

**Comment by spreeker** [comment]
The rollbar account is over it's limits..

**Comment by rrustema** [comment]
Weten we. Johan heeft een free plan aangevraagd zonder limieten als sponsoring.

Heb je het erg nodig nu?

**Comment by spreeker** [comment]
It is handy to see the most urgent matters..

I'm looking into reproducing the error. But I'm pretty sure moving unconfirmed signatures to newsignatures will fix the issue.

**Comment by spreeker** [comment]
Ja nodig want ik kan anders de foutmelding niet achterhalen..

**Comment by spreeker** [comment]
fixed! in  a158ff9076f965749b6c0f5b48511c5a2f1a88c8

**Comment by spreeker** [comment]
I think this is fixed now. I cannot find a single failing signature.. I tried a few on each mentioned petition.

**Comment by rrustema** [comment]
rollbar is now upgraded, should work again
