### ISSUE TITLE
signing petition with .biz e-mail address not possible

### ISSUE THREAD

**Issue by rrustema** [petities/petitions.eu#227]
See complaint at https://opendomein.nl/cerb5/display/LGI-97718-699

Someone tries to sign with a .biz address and it does not appear in new_signatures table and confirmation mail does not go out.

**Comment by skoolstra** [comment]
This is not related to the domain. See example below. Addresses ending with `.biz` are valid in the application. Could this be related to another issue (#232 for example)? 

``` ruby
irb(main):001:0> s = NewSignature.new(person_email: 'john-doe@example.biz', person_name: 'John Doe')
=> #<NewSignature ...>
irb(main):002:0> s.valid?
=> true
```

**Comment by rrustema** [comment]
was probably related to issue 232, the signatory is now in the signatures table, confirmed.
