### ISSUE TITLE
petition view using subdomain address, confirmation e-mail is not sent

### ISSUE THREAD

**Issue by rrustema** [petities/petitions.eu#232]
View a petition using the short link with subdomain, then signing the petition works, but the signature does not show up in table new_signatures table (and no confirmation e-mail goes out). 

Leaving the subdomain by browsing through the list of signatures for example and then chosing 'sign this petition' gives the url with the slug. Then signing works!

**Comment by spreeker** [comment]
it was due to a redirect of post request.

fixed in 4eec97dc972182257d97ce078294c202ee1292bb
