### ISSUE TITLE
legacy urls to petitions should continue to work

### ISSUE THREAD

**Issue by rrustema** [petities/petitions.eu#237]
Old links stopped working. There should at least be a redirect or something.

https://opendomein.nl/cerb5/display/AEI-42756-477

**Comment by spreeker** [comment]
i still dont have an account on that machine.

**Comment by skoolstra** [comment]
Some of the petitions migrated from the legacy application did not have a value in the `slug` field. Even after multiple attempts to have friendly_id calculate it (for example through the `rake petitions:update_slugs` task) the field remained empty. The `cached_slug` field was filled for these petitions. In earlier versions of friendly_id, `cached_slug` was used to reduce queries. I have removed `cached_slug` after setting `slug` with the value. The old link now shows the petition.
