### ISSUE TITLE
status of petition awaiting moderation 

### ISSUE THREAD

**Issue by rrustema** [petities/petitions.eu#238]
petitions with the status awaiting moderation show as not yet finished, which is not accurate

https://opendomein.nl/cerb5/display/ZGP-24823-639 remarks that status should not be 'not yet finished' but 'awaiting moderation'

and so did https://opendomein.nl/cerb5/display/PFN-25591-322 or https://opendomein.nl/cerb5/display/DFK-75458-777

**Comment by skoolstra** [comment]
This issue was created more than one year ago and I am unable to reproduce the error. Please feel free to reopen this bug if the problem still occurs.
