### ISSUE TITLE
details box lay-out of links to petitions

### ISSUE THREAD

**Issue by rrustema** [petities/petitions.eu#239]
currently no visual distinction between the different links, descriptions in text not reliable https://petities.nl/petitions/wereldvredesbond-van-oases-der-menselijkheid/edit?locale=nl

**Comment by skoolstra** [comment]
Unfortunately, I do not understand the problem you are having. If you have time and can still reproduce the bug, please add a more detailed explanation so I can diagnose the problem. Thank you.

**Comment by rrustema** [comment]
Each petition a petitioner can add three links for each petition in the 'details' box under each petition. 

The other items are each one one sentence, occassionally running over a few lines. 

Suggestion. Use the > from the stylesheet when unorderded lists are used (using markdown usually). And also move them up in the list of details since these links require action and are more relevant then the other details, which can then appear underneath the three links. 

Illustrated: current situation and desired situation. Although the lines do not need to be wrapped a a certain lenght anymore. In the example "aankondiging van deze petitie" and "petitie" not on a new line.

![screen shot 2017-12-04 at 16 36 37](https://user-images.githubusercontent.com/98476/33561306-9c5cf94c-d912-11e7-8f6a-8a7eaba2bdce.png)
![screen shot 2017-12-04 at 16 45 34](https://user-images.githubusercontent.com/98476/33561314-a05437fe-d912-11e7-96e0-92f55d4655df.png)

While at it, the distinction 'addressed to' and 'petition desk' is confusing for the end user if these are the same. Currently, those are the same in all 21 cases except under Nederland and Den Haag (except for a rare petition type). Only there it is helpful, in other all other cases the "Addressed to:" label and the organisation value does not need to be shown, as they will be confusing. Just Petition desk and the (clickable) desk name.
