### ISSUE TITLE
fix the signatures list to download

### ISSUE THREAD

**Issue by rrustema** [petities/petitions.eu#242]
if > 10000 "Vraag webmaster@petities.nl om de volledige lijst met ondertekeningen voor deze petitie met meer dan 10.000 ondertekeningen."

name = confirm.form.name.label
city = confirm.form.location.label
function = confirm.form.function.label
csv.confirmed_at = datum ondertekening 

PDF has issues with certain characters?

https://opendomein.nl/cerb5/display/ENU-63953-568 also asks for better formatting. Solution is to offer a completely designed PDF.  See the manual of Prawn. http://prawnpdf.org/manual.pdf

**Comment by skoolstra** [comment]
The export was improved in the last year and I believe all these issues are now resolved.
