### ISSUE TITLE
petitioner can change text of a moderated published petition

### ISSUE THREAD

**Issue by rrustema** [petities/petitions.eu#248]
After moderation of a petition, the petitioner can change the text of the fields: we, observe, request. While the introduction can be changed at any time, these fields are frozen after moderation and can only changed by the admin, petition desk.

Petitioner published news item about having improved a moderated, published petition https://petities.nl/petitions/initiatiefproject-wereldvredesbond-van-oases-der-menselijkheid?locale=nl

Tests give the same result.

**Comment by spreeker** [comment]
also petition desk??
