### ISSUE TITLE
footer

### ISSUE THREAD

**Issue by rrustema** [petities/petitions.eu#25]
- list titles of 10 recent updates (newsitems) with 'show on home'=1 in first column in footer
- second column with Help Start a petition Browse petitions Petition desks Manage your petitions
- third column with News Your privacy About Petities.nl Support us
- DONATE AND SUPPORT PETITIES.NL button spread over 2nd and 3rd column
- fourth column with Address and Contactform

**Comment by rrustema** [comment]
order of content in 2nd and 3rd column needs to be reshuffled

**Comment by rrustema** [comment]
it seems that the last two newsitems are not included in the footer anymore, the two that are visible on the frontpage. Could this be related to resolvement of this issue?

**Comment by skoolstra** [comment]
That behaviour is not related to this issue. Your observation is related to caching. If the first request after the cache key expires was for the homepage, the list will omit the first two. If another was requested the first time after the cache key expired, the first two will be present.

In more detail: please see [_footer.html.slim lines 6-17](https://github.com/petities/petitions.eu/blob/d2c6cd6be59454afeb176f59c4b23753863d8b0a/app/views/shared/_footer.html.slim#L6-L17) for the code used. On line 9 you can see a `offset(2)` being applied when `is_homepage?` is true. When you request this block from the homepage, the first two items will be skipped. The block is fragment cached (`cache @news do` on line 6). All next requests within cache key expiration will just reuse the cached result, without performing the `is_homepage?` condition.
