### ISSUE TITLE
users got disconnected from petition

### ISSUE THREAD

**Issue by rrustema** [petities/petitions.eu#253]
see the case https://opendomein.nl/cerb5/display/NUH-87643-448 who got disconnected from petition. Restored, but there might still be other users with this issue. The issue might still be present, so we have to test the password reset with a petition and petitioner from us.

**Comment by skoolstra** [comment]
This issue was created more than one year ago and I am unable to reproduce the error. Please feel free to reopen this bug if the problem still occurs.

**Comment by rrustema** [comment]
I need to test this a bit more, because I incidentally deal with users who got disconnected from their petition. Might be this issue, perhaps something else.

**Comment by rrustema** [comment]
Another user got disconnected from his new petition https://opendomein.nl/cerb5/display/JNX-52221-337 Twice. The title of the petition did have an accent, but recreating it myself worked (id = 20418). What did this user do? I did not enter a preferred password, perhaps he did? I asked him. Perhaps it is possible to enter a password which is not accepted by the system without a proper error message?

**Comment by skoolstra** [comment]
Removing _after password reset_ from the title. This is caused on creation of new petitions. Marking [petitions_controller.rb lines 181-185](https://github.com/petities/petitions.eu/blob/01a2aa68f4407bd777cd9462d034d4f141197d39/app/controllers/petitions_controller.rb#L181-L185) as the probable cause.

**Comment by rrustema** [comment]
And another one https://opendomein.nl/cerb5/display/MAX-48686-431
