### ISSUE TITLE
number of signatures in petition desk not clear

### ISSUE THREAD

**Issue by rrustema** [petities/petitions.eu#259]
https://opendomein.nl/cerb5/display/AIL-77411-886 says the 11651 signatures mentioned is unclear as the total of signatures for all the petitions signed in this desk.

**Comment by skoolstra** [comment]
What do you propose here? I would vote for removing the total number of signatures from the desks page. The petition desk does not collect signatures. This is only relevant for individual petitions.

**Comment by rrustema** [comment]
Indeed, makes sense.
