### ISSUE TITLE
inaccurate petitions count for each desk in the grid view of desks

### ISSUE THREAD

**Issue by rrustema** [petities/petitions.eu#261]
as in legacy site, now signature count each desk only on the page of the desk itself

**Comment by skoolstra** [comment]
Unfortunately, I do not understand the problem you are having. If you have time and can still reproduce the bug, please add a more detailed explanation so I can diagnose the problem. Thank you.

**Comment by rrustema** [comment]
In the overview with all the petition desks at /petitions/desks we see a grid with 21 petition desks. For each desk the number of petitions for that desk is shown below the name of the desk. In most cases the number does not correspond with the number of petitions shown if the user opens the page for that desk. For example 'Nederland' today has 9910 petities in the grid view, /petitions/desks/nederland shows 7209 in the 'all petitions' sorting. 

The calculation for the grid view should calculate the same number as the one in the 'all' view for that desk.
