### ISSUE TITLE
explain petitioner extra owners might appear

### ISSUE THREAD

**Issue by rrustema** [petities/petitions.eu#270]
related to #264 is the text to the inactive petitioner who is about to see the petition get the orphaned status. There should be a warning that after the original hand over date new owners of the petition might take over the petition. Or are already owner. Sort it out together should be the message. 

Note to self. This can also be a workaround for a petitioner who is seeking co-owners of the petition. Just change the hand over date, have a few signatories with pledges and then they can become co-owner.

**Comment by skoolstra** [comment]
It would be nice to have a list of owners in the `PetitionsController#edit` view. The `:admin` should be able to see a list of all users assigned to her petition.

**Comment by rrustema** [comment]
Indeed, other owners should become visible while they can not edit the data of each other their combined data should show to the outside world (unless they indicated otherwise). This is quite a redesign though. Realistically, next version!

**Comment by johankok** [comment]
On the same subject as #400.
