### ISSUE TITLE
petitioner can start petition without e-mail

### ISSUE THREAD

**Issue by rrustema** [petities/petitions.eu#271]
petitioner can start, save a petition without entering an e-mail address. 
there are petitions in the database not connected to any user. Petitioners try again and again, filling up the database with many duplicate petitions, but we can not connect them to the petitioner. The message says that an e-mail will be sent to the petitioner. Impossible, because no (valid) e-mail was entered.

**Comment by spreeker** [comment]
Last update removed some checks I think.. Also check editing of live
petitions is now possible to.

**Comment by rrustema** [comment]
edit view for petitioner shows for live petitions, petitioner can edit, but after saving the edit is not saved. 
not very elegant, certain fields should not show in edit view for live petitions. With explanation.
