### ISSUE TITLE
1Password and password reset

### ISSUE THREAD

**Issue by rrustema** [petities/petitions.eu#272]
When resetting password and creating a new entry with the 1Password app, the username is not saved. Probably because the username field is missing on the password reset page. Perhaps 1Password can be tricked and the username can be invisible for the end user, but visible for the 1Password (and similar) app.

**Comment by skoolstra** [comment]
This issue was created more than one year ago and I am unable to reproduce the error. Please feel free to reopen this bug if the problem still occurs.
