### ISSUE TITLE
petition desk does not see details

### ISSUE THREAD

**Issue by rrustema** [petities/petitions.eu#273]
petition desk complains https://opendomein.nl/cerb5/display/HTB-76863-122 

the contact details of the petitioner are not visible
in fact, they are, but only after choosing to edit the details (which she did not dare)

fix this by showing name, e-mail, telephone when a petition desk is logged in (but not to users who are not logged in or are not the petition desk for this petition).

**Comment by skoolstra** [comment]
This issue was created more than one year ago and I am unable to reproduce the error. Please feel free to reopen this bug if the problem still occurs.
