### ISSUE TITLE
password reset for confirmed account sends e-mail to confirm account

### ISSUE THREAD

**Issue by rrustema** [petities/petitions.eu#275]
even though an account is already confirmed, after a password reset, still a confirm e-mail is sent. 
does not make sense, because how could the user otherwise get the reset password link? Only by a working e-mailaddress. 

In other words, resetting your password should implicitly also be a way to confirm your e-mail address.

**Comment by skoolstra** [comment]
This issue was created more than one year ago and I am unable to reproduce the error. Please feel free to reopen this bug if the problem still occurs.
