### ISSUE TITLE
petitioner does not see why live petition can not be editted

### ISSUE THREAD

**Issue by rrustema** [petities/petitions.eu#277]
petitioner can not edit live petition. The edit view should not even appear for a live petition, as it does now. And it should be explained why certain fields can not be changed after the petition is live.

**Comment by spreeker** [comment]
#87991d7

It was in there. Got reverted by kooistra

petitioner can not edit live petition The edit view should not even appear
for a live petition, as it does now And it should be explained why certain
fields can not be changed after the petition is live

—
Reply to this email directly or view it on GitHub
https://github.com/petities/petitions.eu/issues/277.
