### ISSUE TITLE
some users do not see the values in input fields

### ISSUE THREAD

**Issue by rrustema** [petities/petitions.eu#280]
complaint from a civil servant in Amsterdam, probably using an outdated IE version for Windows NT or XP. https://opendomein.nl/cerb5/display/XWA-93578-835

But also those with disabilities should see labels above each input field so their special equipment can read it out to them.

![image001](https://cloud.githubusercontent.com/assets/98476/12718955/69a68428-c8f2-11e5-9e85-f88a4713e5b8.jpg)

**Comment by skoolstra** [comment]
This issue was created over a three years ago and I am unable to reproduce the error. Please feel free to reopen and update this report if the problem still occurs.
