### ISSUE TITLE
new_signatures tables misses signature_remote_addr and signature_remote_browser

### ISSUE THREAD

**Issue by rrustema** [petities/petitions.eu#281]
the fields signature_remote_addr and signature_remote_browser are useful to help a user with complaints, they show in the signatures table, but not in the new_signatures table.

**Comment by spreeker** [comment]
won't fix.

**Comment by rrustema** [comment]
https://opendomein.nl/cerb5/display/XUQ-85355-772 another example why this needs a fix. Signatory asks who signed. Her ip-address is in the header of the e-mail. This can easily be solved if IP-address of sign attempt is the same.
