### ISSUE TITLE
Improve text on contact form page

### ISSUE THREAD

**Issue by rrustema** [petities/petitions.eu#295]
text on contact form should be improved to discourage marketeers/spammers to approach us by e-mail, with reference to Dutch laws about spam. 

https://opendomein.nl/cerb5/display/VXM-85115-299
https://opendomein.nl/cerb5/display/NIP-35431-167

**Comment by skoolstra** [comment]
This issue was created over three years ago and I am unable to reproduce the error. Please feel free to reopen and update this report if the problem still occurs.
