### ISSUE TITLE
character limit without error in open input field for pledge

### ISSUE THREAD

**Issue by rrustema** [petities/petitions.eu#298]
There is one open text input field for pledges on the signature confirmation page. Any input less than 210 characters gets a 'thank you' flash message. Anything above gets no thank you and no error message. Input also does now appear in the database. 

At least there should be an error when exceeding a text limit, preferably there is no low text limit. Perhaps 1000 words. 

https://opendomein.nl/cerb5/display/JMH-33844-657 demonstrated this issue by sending in a wordy pledge by e-mail.

**Comment by skoolstra** [comment]
Validation on length for `Plegde.feedback` was added.  Reopening because it still needs a solution in the user interface.
