### ISSUE TITLE
different pictures above petition view and signatures view

### ISSUE THREAD

**Issue by rrustema** [petities/petitions.eu#301]
when a petitioner uploaded several pictures to decorate the petition, the last one is shown on the petition sign view and the previous one on the signatures list view. 

See https://opendomein.nl/cerb5/display/BMH-48361-764

The user shared the petition on Facebook which grabs the picture it finds and the user noticed the difference. 

https://petities.nl/petitions/steun-voor-wilders-van-pvv-ers/signatures?locale=nl

https://petities.nl/petitions/steun-voor-wilders-van-pvv-ers?locale=nl

**Comment by skoolstra** [comment]
Closing this issue, because this was resolved a while ago. The last uploaded image is used on both pages. Please feel free to reopen when you do not agree.
