### ISSUE TITLE
e-mail to petitioner misses name and username 

### ISSUE THREAD

**Issue by rrustema** [petities/petitions.eu#307]
After creating a petition the petitioner receives an e-mail with "Verder met uw petitie" in the subject. 

Missing in those e-mails are the name and username. 

For example https://opendomein.nl/cerb5/display/ESD-93732-563

**Comment by skoolstra** [comment]
This issue is a duplicate of #429 and was resolved in 14eb288b4abe3d93e7088cf5b54fe85059b642e3.
