### ISSUE TITLE
uploading pictures with spaces in filename

### ISSUE THREAD

**Issue by rrustema** [petities/petitions.eu#313]
When user https://opendomein.nl/cerb5/display/ERQ-12969-342 uploads picture with filename with spaces, then the error 'sorry, something went wrong'. Filename without spaces is no problem. 

What are the requirements of a filename? 
How can we make this user friendly?

**Comment by skoolstra** [comment]
The validation on image filename only restricts the used extensions. A space is allowed in the filename. Filename validations are case sensitive. The image was probably rejected because the extension was all uppercase (`.JPG`).

**Comment by skoolstra** [comment]
Closing this issue, as the fix was deployed days ago. Please feel free to reopen if you encounter this again.
