### ISSUE TITLE
activity value broken?

### ISSUE THREAD

**Issue by rrustema** [petities/petitions.eu#324]
there is a new petition with one page of signatures put within the last hour, https://petities.nl/petitions/behoud-contant-geld-voor-onze-privacy-en-vrijheid?locale=nl nevertheless it does not show in the active petitions grid view. 

the active petitions have days old signatures. For example https://petities.nl/petitions/tegen-bomenkap-en-herplant-platanen-aan-de-zoomwijcklaan-oud-beijerland/signatures?locale=nl

is the activity value accurate?

**Comment by spreeker** [comment]
Its averaged over 15 days now.
