### ISSUE TITLE
stats include today

### ISSUE THREAD

**Issue by rrustema** [petities/petitions.eu#325]
The statistics graphic next to a (live) petition include today. It should not go further than mid night yesterday. If it includes today the trend shown by the graphic nearly always goes downward, simply because the day is not yet finished and rarely more signatures are collected at any given moment during the day as during the entire day yesterday. Except perhaps in the late evening. Petitions which are exploding in popularity might even show that it levels with yesterday. 

Few visitors study the dates of each bar, they give the graphic a quick glance to see the trend.

**Comment by rrustema** [comment]
![screen shot 2016-02-24 at 00 17 56](https://cloud.githubusercontent.com/assets/98476/13270136/5603adaa-da8c-11e5-8af7-bed60ceb1704.png)

Today is still shown in the graphic, although no bar with signatures appear while there are signatures today. Perhaps this starts to show after midnight. The screen shot is taken a little after midnight. No signatures appear yet, perhaps because the uncorrected time on the server or of signatures in the database is used instead of the real time? http://Anee9.petities.nl

In the most popular petition http://nexitreferendum.petities.nl currently there are 36 pages with 100 signatures each collected in one day today. Yet the graph shows only 100 for today. 

Whatever is going on, the stats are unreliable. It is not clear what they show.

**Comment by spreeker** [comment]
I'd like to see my current 'today' progress when i did my own petition,  We could change the last label to TODAY or vandaag.

**Comment by rrustema** [comment]
Let's first improve the labels indeed: today, yesterday, last week.

**Comment by rrustema** [comment]
still an issue. In the next version we should have more meaningful graphs anyway.
