### ISSUE TITLE
in English grid view shows oldest version of petitions

### ISSUE THREAD

**Issue by rrustema** [petities/petitions.eu#328]
In the grid view of petitions and in the e-mails sent out, the name of the petition is taken from the oldest version of the petition rather the latest. 

Then you see 'EU referendum' instead of the corrected 'E. U. Referendum' in the name for example. Or 'Stop explosieve groei intensieve veehouderij in Drenthe' instead of 'test' (a petition which was a modified test petition). 

At first I thought it was related to the chosen locale, but in this screenshot you can see it also appears in Dutch. A reload of the page made this disappear. 

![screen shot 2016-02-24 at 14 01 02](https://cloud.githubusercontent.com/assets/98476/13286109/43d2963c-daff-11e5-8cea-cf61c4fded98.png)

**Comment by spreeker** [comment]
When there is no explicit english/locale version, the fallback behaviour kicks in. Which apparently takes the oldest version. 

It should be more obvious in the edit page to create and English version for the petition.
