### ISSUE TITLE
user with an unavailable prefered language in browser gets an error everywhere

### ISSUE THREAD

**Issue by rrustema** [petities/petitions.eu#329]
A user https://opendomein.nl/cerb5/display/GMP-99577-294 with German (de) as primary language set in the browser client (probably) gets the error "de.petition.we_could_not_find_petition_try_search". Or is something else the problem?

Needs further testing with a browser set to a language other than Dutch or English. Who would like to do this?

**Comment by skoolstra** [comment]
Please see before_action [set_locale](https://github.com/petities/petitions.eu/blob/4cf6b58fb98dbf08ba1ace038d26cca0557526a1/app/controllers/application_controller.rb#L67-L79) in ApplicationController for the implementation. The language will be picked from a list of languages available, based on the `?locale=` part of the URL or the language preference received from the browser. The `I18n.default_locale` will be used if the requested language is not available. You can find the settings for default locale in [config/application.rb](https://github.com/petities/petitions.eu/blob/9f0273d462ba33142c653321a999ca747ee698c4/config/application.rb#L24).

German is listed in the `available_languages` and will be used if the user prefers it. The key `petition.we_could_not_find_petition_try_search` was not present in the German language file. I could not find the key in any other language file either.

**Comment by spreeker** [comment]
Add error URLs.

**Comment by spreeker** [comment]
I think it is an deployment issue with an old gunicorn process handling the
request. I can reproduce the error with locale=de only sometimes.

**Comment by skoolstra** [comment]
Closing this issue. If you encounter this again, please feel free to reopen.
