### ISSUE TITLE
password reset e-mail needs internationalisation

### ISSUE THREAD

**Issue by rrustema** [petities/petitions.eu#345]

**Comment by skoolstra** [comment]
The [devise-i18n](https://github.com/tigrish/devise-i18n) gem provides default translations for the password reset. You can find the translation keys to use for customisation in [reset_password_instructions.html.erb](https://github.com/tigrish/devise-i18n/blob/v1.0.1/app/views/devise/mailer/reset_password_instructions.html.erb) template inside `devise-18n`. 

The default text is now used (both in Dutch and English). You can just add the translations in our language files to change the message.

**Comment by skoolstra** [comment]
This issue was created more than one year ago and I am unable to reproduce the error. Please feel free to reopen this bug if the problem still occurs.
