### ISSUE TITLE
mailtrap stopped working locally

### ISSUE THREAD

**Issue by rrustema** [petities/petitions.eu#346]
to test e-mail functionality we used to work with mailtrap.io, but now:

Errno::ECONNREFUSED at /contact
Connection refused - connect(2) for "mailtrap.io" port 2525

where to configure this?

**Comment by spreeker** [comment]
We have previews now? The mailtrap mailbox is full probably.

**Comment by spreeker** [comment]
Or you have a firewall or something.. Its in the settings file With all other settings. On maiotrap.io are instructions.

**Comment by skoolstra** [comment]
Mailtrap.io works for me. I agree this is probably caused by a firewall blocking port 2525 at your location. You could try using http://mailcatcher.me/, which runs locally.

**Comment by rrustema** [comment]
Yes, it was the location I was at. Not at home or at work.
