### ISSUE TITLE
improved search function

### ISSUE THREAD

**Issue by rrustema** [petities/petitions.eu#349]
users continue to complain about the search function, for example https://opendomein.nl/cerb5/display/JYY-75135-757 This user searched for two words in the title of his petition and got zero results. Using either word gives the petition as a result.

Without a good understanding about how this one is configured the results are usually disappointing, suggesting that a certain petition does not exist (on this website). 

At least there should be a message next to the search results explaining how to get better results.

**Comment by johankok** [comment]
Duplicate of #251.
