### ISSUE TITLE
petition desk should see contact info petitioner

### ISSUE THREAD

**Issue by rrustema** [petities/petitions.eu#37]
A petition desk should be able to see the contact information from a petitioner. Under 'details', e-mail and phonenumber. From the personal data users can enter under 'My profile'. In practise the phone number is added by the moderator based on number recognition when the user leaves a voicemail. Voluntarily users do not add their phone number.

**Comment by spreeker** [comment]
I need a little more guidance on this one.

If I understand correctly the details field in a petition page should be expanded with extra information about the petitioner if available? and only if the viewer is an admin or petitioner.
