### ISSUE TITLE
update signature button under iOS 

### ISSUE THREAD

**Issue by rrustema** [petities/petitions.eu#373]
in Dutch the translation of the Update my signature button on the confirmation page is not finished.

![screen shot 2016-04-03 at 12 18 34](https://cloud.githubusercontent.com/assets/98476/14231946/3a473e6e-f996-11e5-8f8c-751ea92889a8.png)

**Comment by skoolstra** [comment]
This issue was created more than one year ago and I am unable to reproduce the error. Please feel free to reopen this bug if the problem still occurs.
