### ISSUE TITLE
error message needs translations in live petition edit view

### ISSUE THREAD

**Issue by rrustema** [petities/petitions.eu#377]
When petitioner tries to edit a live petition there is an error popping up. But this is not yet translated. 

![schermafbeelding 2016-04-03 om 15 31 51](https://cloud.githubusercontent.com/assets/98476/14234972/e6af897c-f9f0-11e5-87de-e8351bb7500f.png)

**Comment by skoolstra** [comment]
This issue was resolved in a2c0fc9.
