### ISSUE TITLE
iOS user with account @mac.com does not see body of confirmation e-mail

### ISSUE THREAD

**Issue by rrustema** [petities/petitions.eu#378]
See https://opendomein.nl/cerb5/display/AZW-88692-289 with the complaint. Another had a similar complaint. Both with:

Received: from pv33p00im-smtpin019.me.com ([17.142.194.210]) by ms18554.mac.com (Oracle Communications Messaging Server 7.0.5.36.0 64bit (built Sep  8 2015))

**Comment by skoolstra** [comment]
This issue was created almost one year ago. I cannot reproduce this and will presume it was resolved. Please reopen this issue if the problem still exists.
