### ISSUE TITLE
the value for the last 1000 signatures, not the first 900 

### ISSUE THREAD

**Issue by rrustema** [petities/petitions.eu#379]
to solve issue #333 I need to reverse the result of the value @all_signatures. 

Currently in line 18 of the signatures_controler.rb it says     

`@all_signatures = @petition.signatures.confirmed.limit(900)`

What to add to this line to make it return not the first 900 but the last 1000 signatures?

**Comment by spreeker** [comment]
limit(1000)

**Comment by rrustema** [comment]
the last 1000 signatures instead of the first 1000, that's what I need to know
Currently the list gives the first 900, but if the petitioner can download the last 1000, we do not have to supply a list of 1000+ manually because they can collect them in batches of 1000.

**Comment by spreeker** [comment]
http://stackoverflow.com/questions/420352/how-to-get-last-n-records-with-activerecord

how about..  .last(1000)

**Comment by rrustema** [comment]
Yes!  That works! Thanks. It gives the last 1000 based on id rather than date of confirmation, but that will do. 

line 18:

`@all_signatures = @petition.signatures.confirmed.last(1000)`

But it works only when I delete the 'else' condition in the ajax request in lines 59-62. Which breaks other functionality I appreciate. Like the full list of signatures of a petition. Lines 59-62:

`

```
if request.xhr?
  @signatures = @all_signatures
                  .order(special: :desc, confirmed_at: :desc)
                  .paginate(page: @page, per_page: @per_page)
else
  @signatures = @all_signatures
                  .order(special: :desc, confirmed_at: :desc)
                  .paginate(page: @page, per_page: @per_page)
end
```

`

Which looks a bit strange to me. The if and the else are the same. Is that proper code? Isn't there a more beautiful way to solve this? Perhaps not with an if and else construction?

**Comment by skoolstra** [comment]
The export size was increased to 5000 in d9cff4b. Please reopen this issue if that change did not solve your issue.
