### ISSUE TITLE
One click copying of copy-paste share link

### ISSUE THREAD

**Issue by rrustema** [petities/petitions.eu#39]
the share link now needs to be manually selected copied and pasted when sharing. In the legacy site there was a gadget for the admin to copy it with one click. 

Discussion about wether this is possible without Flash (because of tablets and phones) here http://stackoverflow.com/questions/22581345/click-button-copy-to-clipboard-using-jquery

**Comment by skoolstra** [comment]
The share buttons were updated one month ago. That change did not introduce one click copying of the URL, but I do not believe this is required anymore. Please reopen if you feel that function should be included.
