### ISSUE TITLE
content of new petition also in petitions field

### ISSUE THREAD

**Issue by rrustema** [petities/petitions.eu#402]
not only in petitions_translations, but the first version of a petition should also be in the petitions field (like the legacy petitions) to make the management of petitions easier. To distinguish between different petitions in the database. 

Not visible for anyone except admin with database access.

**Comment by skoolstra** [comment]
This issue can not be resolved. These fields are translated and therefore stored in the `petitions_translations` table. The website could provide a interface for admins that eliminates the need for database access.
