### ISSUE TITLE
older petition shows unconfirmed signatures in grid view

### ISSUE THREAD

**Issue by rrustema** [petities/petitions.eu#411]
petition 16936 has 6 signatures, 5 confirmed. In grid view (immediately under the petition) all 6 are visible, in list view only the 5 confirmed. The unconfirmed uses an e-mail address that won't work. 
https://opendomein.nl/cerb5/display/ALF-86136-255

Question: do all petition have this? Or only those from before 28-12-2015

**Comment by skoolstra** [comment]
Please see the [action `show` inside `PetitionsController`](https://github.com/petities/petitions.eu/blob/d2c6cd6be59454afeb176f59c4b23753863d8b0a/app/controllers/petitions_controller.rb#L160-L162) for the answer. All records from the `signatures` table for a petition are rendered in the grid. This website stores signatures before confirmation in `new_signatures`. 

Unconfirmed signatures are only listed for petitions migrated from the previous website. These were all created before 28-12-2015. I propose we remove them. Do you agree?

**Comment by rrustema** [comment]
we can perform an analysis on the success ratio of confirmation since the new website in other ways, so let's get rid of those unconfirmed signatures in the signatures table. Might also speed up things.

**Comment by skoolstra** [comment]
Thanks, they have been removed.
