### ISSUE TITLE
not all signatories can be made prominent

### ISSUE THREAD

**Issue by rrustema** [petities/petitions.eu#412]
https://opendomein.nl/cerb5/display/CRC-51498-156 but also another petitioner complained that a certain signatory can not be promoted to prominent. 

Through ActiveAdmin, choosing the checkbox Special does work though.

**Comment by spreeker** [comment]
- cache
- network
- anonymous.!! But administration so can see the name..

**Comment by rrustema** [comment]
signature 6291745 did not sign petition 3016 anonymously. Petitioners can not lookup anonymous signaturories since they are only visible in grid view under the petition. 

How could cache and network be relevant if making other signatories prominent in the same session is no issue?

**Comment by skoolstra** [comment]
This issue was created more than one year ago and I am unable to reproduce the error. Please feel free to reopen this bug if the problem still occurs.
