### ISSUE TITLE
Facebook sharing is broken

### ISSUE THREAD

**Issue by rrustema** [petities/petitions.eu#413]
Possibly after resolving issue #172 this error was introduced. Facebook sharing gives an error.

**Comment by rrustema** [comment]
https://opendomein.nl/cerb5/display/AXR-48899-867 is the ticket about it
and another complaint https://opendomein.nl/cerb5/display/AZN-81476-581

**Comment by skoolstra** [comment]
I pushed a quick fix that should resolve this issue. Can you confirm this and inform the users? Thank you.

**Comment by spreeker** [comment]
@rrustema I remember you kind of 'hating' facebook not long ago :)

**Comment by rrustema** [comment]
Still the case. Avoid when possible. Hopefully this share tool does not communicate with/ enrichens Facebook servers when just viewing the page. Still on my todo list to check that thoroughly. 

ReindeR
