### ISSUE TITLE
counter of petition signatories inaccurate

### ISSUE THREAD

**Issue by rrustema** [petities/petitions.eu#414]
https://opendomein.nl/cerb5/display/AAG-38279-357 

perhaps a script should reset counters of petitions in the petitions table once a week or so and then recalculate the count based on a database query. Because the plus 1 after each signature gives a tiny inaccuracy.

**Comment by spreeker** [comment]
I'm pretty sure there is a daily task for that..

**Comment by rrustema** [comment]
Petition 18020 has count 14865 in the database, while 14922 are shown on the petition page by the counter.

**Comment by skoolstra** [comment]
Signature counters were moved to redis and the daily task did not take that into account.
