### ISSUE TITLE
shared petitions illustrated with irrelevant image

### ISSUE THREAD

**Issue by rrustema** [petities/petitions.eu#415]
When sharing a petition on a social network the petition is illustrated with an image. Too often (a part of) the sponsor logo is used instead of the image uploaded by the petitioner. Or, if this is not the case, the logo of the site. 

Facebook wants us to include code to describe objects, 
https://developers.facebook.com/docs/sharing/opengraph/using-objects

but perhaps there is some more generic structure possible that works also for the other and future social networks and sharing tools?

**Comment by tttp** [comment]
No, twitter and FB have a different structure, unfortunately.
What we come up with that seems to work (assuming the image is big enough):

```
   <meta property="og:title" content="petition title" />
   <meta name="description" content="Bla bla bla" />
   <meta property="og:image" content="bla.jpg">
   <meta name="twitter:card" content="summary_large_image" />
   <meta name="twitter:title" content="petition title" />
   <meta name="twitter:description" content="Bla bla bla" />
   <meta name="twitter:image" content="bla.jpg">
   <meta name="twitter:site" content="@eucampaign">
   <meta name="twitter:creator" content="@eucampaign">

```

**Comment by rrustema** [comment]
Thanks, we will just adapt to Facebook I propose. On Twitter there is no issue because we do not post a picture there. Actually, our Facebook message is a tweet that is reposted to Facebook to make updates about new petitions easy, automated. https://www.facebook.com/petitiesnl-225251577526395/

**Comment by tttp** [comment]
I would recommend to put both, as it is what is used as well when a
signatory shares the link too

**Comment by rrustema** [comment]
Yes, now we only have to do it :-)

**Comment by tttp** [comment]
I'm trying to install the sofware, it might be my first PR if I find my way in the code

**Comment by skoolstra** [comment]
I added some Open Graph meta tags to improve sharing on these social networks. Please feel free to improve on that.

**Comment by skoolstra** [comment]
This issue was resolved some time ago. Please feel free to reopen if the problem still exists.

**Comment by rrustema** [comment]
Logo of sponsor now only appears when a petition is shared which was not given a picture by the petitioner. A kind of sanction... Good.
