### ISSUE TITLE
delete_all never called upon

### ISSUE THREAD

**Issue by rrustema** [petities/petitions.eu#416]
Upon studying the code it seems that delete_all as defined in these lines:
https://github.com/petities/petitions.eu/blob/master/lib/tasks/petition.rake#L54-L66
is never called upon in the rest of the code? What was the original intention there?

**Comment by spreeker** [comment]
The code is there to delete all Keys. Only In case some super duper programmer fucks things up / debugging is needed / nasty bugs adds many invalid Keys this function comes in handy to clean things up :).

Each petition can delete its own Keys.(or should be able to) and in normal operation this is not needed.

Also 'delete_all' used to be the simpel aproach to delete and then rebuild all keys each time. BUT it leaves the site With invalid counters for quite some time...
so each petition should delete it s onw Keys now and this function is there just in case shit hits the fan.
