### ISSUE TITLE
How to create (admin) users?

### ISSUE THREAD

**Issue by tttp** [petities/petitions.eu#417]
Hi,

So I've been trying to create various users and admin_users from the console, but I might miss to create roles and in general, not sure what the site admin should see, so not super sure I test the right way.

In short: how to create a superuser and where is the admin panel?

**Comment by skoolstra** [comment]
The User model is used for users of the website (creator of a petition, for example). Users can have multiple roles. The AdminUser model is used to access the ActiveAdmin panel for site-wide admin operations and maintenance.

**User**
The user model requires confirmation link of the email address. To create a User for your development environment and skip the confirmation step: 

``` ruby
user = User.new(email: 'admin@example.com', password: 'password')
user.skip_confirmation!
user.save
```

Now you can apply the admin role to this user with `user.add_role(:admin)`.

**AdminUser**
In the console you can use `AdminUser.create(email: 'admin@example.com', password: 'password')` to create your first admin user. You can find a link to the panel in the user menu after you login with your User account. The path for the ActiveAdmin panel is /yesmaster/admin.

**Comment by tttp** [comment]
Works fine, thanks.
