### ISSUE TITLE
Feedback on rejected petitions like concluded petitions

### ISSUE THREAD

**Issue by rrustema** [petities/petitions.eu#42]
The feedback on rejected petitions should also be visible on the website, just like the feedback on concluded petitions. This is a special newsupdate written by the moderator.

**Comment by spreeker** [comment]
there are 25 feedback items in my database. it is not used in enough to fix now I think.

what and where are we going to do answers to petitions from target organizations?

**Comment by rrustema** [comment]
the table feedback in the database is not used anymore. Instead use the newsitems table with an extra value 'answer'.  This answer will also appear next to that particular petition, where the box to sign would otherwise float if the petition is open for signing.

**Comment by skoolstra** [comment]
This issue seems to be outdated. You can write a newsitem for rejected petitions and mark ik to be displayed next to the text, identical to answered or concluded petitions. Closing this issue, please feel free to reopen if the problem persists.

**Comment by rrustema** [comment]
Will try that with existing rejected petitions and will revisit this issue if it does not work. We might need some line looking at the combination rejected + answer and rephrase the presentation.
