### ISSUE TITLE
Settingslogic: Have per install configuration options

### ISSUE THREAD

**Issue by tttp** [petities/petitions.eu#420]
Hi, to solve #419, I'd like to make easy to have configuration per install, stuff like the domain name, enabling/disabling some features, different layouts...

so under config, have two settings files: default_settings.yml and settings.yml

default_settings contains anything that is generic and should work out of the box, it's merged with settings that contains the install specific config (eg name of the site, url...). default_settings.yml is on git, settings.yml is .gitignored

Make sense? PR welcome? I'm trying locally, just so I stop forking and sed -i s/petities.ml/mydomain ;)

**Comment by tttp** [comment]
@johankok or @skoolstra, could you ok the principle?

**Comment by spreeker** [comment]
makes sense. There are a lot of references to petities.nl in translation files to I think..
