### ISSUE TITLE
signatures_count inaccurate

### ISSUE THREAD

**Issue by rrustema** [petities/petitions.eu#440]
The signatures_count for petition 21261 is 5133, in the petition view on https://petities.nl/petitions/er-moet-meer-geld-naar-wetenschappelijk-onderwijs/ it says 4668, but counting the number of signatures in the signatures table gives 5158 signatures. 

Perhaps this also affects other petitions? Due to incidental redis issues in December around the time of closing this petition or structural?

As a workaround I changed the content of the petition page, as well as with live as with in_process status. As an attempt to invoke the script updating the cached version of the petition view. No result yet. 
![screen shot 2018-01-31 at 15 35 03](https://user-images.githubusercontent.com/98476/35628485-58f8389e-069c-11e8-8472-541cf7951eb1.png)

**Comment by skoolstra** [comment]
This is a known issue. There are inconsistencies in the code that allow the redis signature counter to remain inaccurate for closed petitions. 

I have updated all counters for closed petitions. A fix for the actual problem will follow on a later date.
