### ISSUE TITLE
No .ru e-mailaddress suggestions

### ISSUE THREAD

**Issue by rrustema** [petities/petitions.eu#452]
The code at petitions.eu/app/assets/javascripts/signature.coffee suggeste to a certain user a domain ending in .ru instead of the .nu domain her e-mail address is on.

This is not desirable for obvious reasons.  

See ticket https://opendomein.nl/cerb5/display/MPZ-98883-564 for details.

**Comment by skoolstra** [comment]
Would you be able provide a complete list of top-level domains appropriate for this application? You could base it on the [default list](https://github.com/mailcheck/mailcheck/blob/cbc33a6f1af79c70f8d4a0dfc0b0140b7cd5f9cf/src/mailcheck.js#L31-L34) that is included in mailcheck.js. Thanks.

**Comment by rrustema** [comment]
From the TLDs in the default list that are likely to confuse rather than help the majority of our end users are: 

`"com.au", "com.tw", "ca", "co.nz", "co.uk", "it", "ru", "edu", "gov", "jp",  "kr", "se", "eu", "ie", "co.il", "us", "at",  "dk", "hk", "es", "gr", "ch", "no", "cz", "in", "net.au", "info", "biz", "mil", "co.jp", "sg", "hu", "uk"`

in other words, only the major global TLDs and the ones of neighbouring countries where Dutch residents have a (second) home are useful as a suggestion:  

`"com", "net", "org", "be", "de", "fr", "nl"
`

After all, this is only a suggestion and end-users with something other than nl etc. as TLD, for example .edu, can still sign.
