### ISSUE TITLE
petition due date mailing

### ISSUE THREAD

**Issue by spreeker** [petities/petitions.eu#72]
- **warning** petition reaches due date in one week and has less than 10 signatures or no signatures the last month, then send an e-mail asking to change due date or it will automatically be revoked
- **failed** petition reaches due date but with less than 10 signatures, then change status to withdrawn it
- **need answer or orphan** petition status changes to to_process at due date, send an announcement to recipient of petition with request for an answer and a reference number, unless petitioner did not write news updates, then status = orphan

**Comment by spreeker** [comment]
added previews c7c2e21ae377695074e63dbe5c14ecea469bf3a0

**Comment by rrustema** [comment]
flowchart with what happens at https://www.lucidchart.com/documents/edit/02c38405-3ac5-4071-a2ef-64355b9b14f6#
