### ISSUE TITLE
adoption / survey page about a petition

### ISSUE THREAD

**Issue by spreeker** [petities/petitions.eu#76]
Get feedback from audience.

**Comment by rrustema** [comment]
Options for survey to check:
1. request of petition has been met, no need for petition anymore
2. petition came too late 
3. the situation has changed, petition needs to change too
4. the political majority disagrees, there is no point to continue now
5. we should continue differently: organise ourselves, hire a lawyer, etc.
6. I personally can not adopt the petition (too busy or not my thing)
7. Other: [     ]

The popularity of these options should then appear in a news update under the petition once the status changes to withdrawn. The input for the open question is not published, only the frequency of it. Those texts are stored in the database and can be added manually after moderation.

**Comment by rrustema** [comment]
adoption_request_signatory_mail (see preview) already mentions these options which are internationalised under :survey: in the yml files. So people can also send in their response by e-mail. But a link to a survey page would improve things.
