### ISSUE TITLE
petitioner promotes signatories to prominent

### ISSUE THREAD

**Issue by rrustema** [petities/petitions.eu#92]
by clicking on the 'star' icon or perhaps even by dragging the signatures in the grid view the petitioner can sort the order of appearance of signatories under the petition

**Comment by skoolstra** [comment]
This was resolved in 0c141f029230a09aefc331bf1af69057cdbba6b4. A petitioner can influence the sorting of the list by appointing signatures as `special`. The field `sort_order` for more complex sorting is not used.
